// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSystem.Data.Data;

#nullable disable

namespace SchoolSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230630152249_FirstOne")]
    partial class FirstOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.Property<int>("AlunosIdAluno")
                        .HasColumnType("int");

                    b.Property<int>("TurmasIdTurma")
                        .HasColumnType("int");

                    b.HasKey("AlunosIdAluno", "TurmasIdTurma");

                    b.HasIndex("TurmasIdTurma");

                    b.ToTable("AlunoTurma");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluno"));

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.HasKey("IdAluno");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Materia", b =>
                {
                    b.Property<int>("IdMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateria"));

                    b.Property<int>("MateriaCode")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaIdTurma")
                        .HasColumnType("int");

                    b.HasKey("IdMateria");

                    b.HasIndex("TurmaIdTurma");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Turma", b =>
                {
                    b.Property<int>("IdTurma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurma"));

                    b.Property<int>("Materia")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.HasKey("IdTurma");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.HasOne("SchoolSystem.Models.Models.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunosIdAluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolSystem.Models.Models.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmasIdTurma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Materia", b =>
                {
                    b.HasOne("SchoolSystem.Models.Models.Turma", null)
                        .WithMany("Materias")
                        .HasForeignKey("TurmaIdTurma");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Turma", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
