// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolSystem.Data.Data;

#nullable disable

namespace SchoolSystem.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230720160649_aoadoawadada")]
    partial class aoadoawadada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolSystem.Models.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serie")
                        .HasColumnType("int");

                    b.Property<int?>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Matricula = "222",
                            Name = "Rodrigo",
                            Senha = "2",
                            Serie = 3
                        },
                        new
                        {
                            Id = 2,
                            Matricula = "333",
                            Name = "Ronaldo",
                            Senha = "3",
                            Serie = 3
                        },
                        new
                        {
                            Id = 3,
                            Matricula = "444",
                            Name = "Manuela",
                            Senha = "4",
                            Serie = 5
                        },
                        new
                        {
                            Id = 4,
                            Matricula = "555",
                            Name = "Fernando",
                            Senha = "5",
                            Serie = 2
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoMateria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTeste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunosId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Turmas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "11"
                        },
                        new
                        {
                            Id = 2,
                            Name = "12"
                        },
                        new
                        {
                            Id = 3,
                            Name = "13"
                        },
                        new
                        {
                            Id = 4,
                            Name = "21"
                        },
                        new
                        {
                            Id = 5,
                            Name = "22"
                        },
                        new
                        {
                            Id = 6,
                            Name = "23"
                        },
                        new
                        {
                            Id = 7,
                            Name = "31"
                        },
                        new
                        {
                            Id = 8,
                            Name = "32"
                        },
                        new
                        {
                            Id = 9,
                            Name = "33"
                        },
                        new
                        {
                            Id = 10,
                            Name = "41"
                        },
                        new
                        {
                            Id = 11,
                            Name = "42"
                        },
                        new
                        {
                            Id = 12,
                            Name = "43"
                        },
                        new
                        {
                            Id = 13,
                            Name = "51"
                        },
                        new
                        {
                            Id = 14,
                            Name = "52"
                        },
                        new
                        {
                            Id = 15,
                            Name = "53"
                        });
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Aluno", b =>
                {
                    b.HasOne("SchoolSystem.Models.Models.Turma", null)
                        .WithMany("Alunos")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Atividade", b =>
                {
                    b.HasOne("SchoolSystem.Models.Models.Aluno", "Aluno")
                        .WithMany("atividades")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Aluno", b =>
                {
                    b.Navigation("atividades");
                });

            modelBuilder.Entity("SchoolSystem.Models.Models.Turma", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
